<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProfesorSeeder extends Seeder
{
    public function run(): void
    {
        $profesores = [

            // ══════════════════════════════════════════════════════════════
            // JORNADA MATUTINA
            // Director: Edwin Orlando Amador Mejia
            // ══════════════════════════════════════════════════════════════

            [
                'nombre'         => 'Jennifer Jeanneth',
                'apellido'       => 'Mascareño Mairena',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '1°',
                'seccion'        => '1',
                'aula'           => 9,
                'jornada'        => 'Matutina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1990-00001',
                'fecha_nacimiento'=> '1990-01-01',
                'fecha_ingreso'  => '2020-01-15',
            ],
            [
                // Nota: en la imagen aparece tachada "Ana Melissa Valladares Castillo"
                // y sustituida por "Concepción Jamilhd Sierra"
                'nombre'         => 'Concepción Jamileth',
                'apellido'       => 'Sierra',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '1°',
                'seccion'        => '2',
                'aula'           => 2,
                'jornada'        => 'Matutina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1991-00002',
                'fecha_nacimiento'=> '1991-03-15',
                'fecha_ingreso'  => '2023-01-10',
            ],
            [
                'nombre'         => 'Juana Magdalena',
                'apellido'       => 'León Centeno',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '2°',
                'seccion'        => '1',
                'aula'           => 1,
                'jornada'        => 'Matutina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1985-00003',
                'fecha_nacimiento'=> '1985-06-20',
                'fecha_ingreso'  => '2015-02-01',
            ],
            [
                'nombre'         => 'Liz Dionelsy',
                'apellido'       => 'Veliz Escoto',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '2°',
                'seccion'        => '2',
                'aula'           => 4,
                'jornada'        => 'Matutina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1988-00004',
                'fecha_nacimiento'=> '1988-09-10',
                'fecha_ingreso'  => '2018-03-01',
            ],
            [
                'nombre'         => 'Paula Melissa',
                'apellido'       => 'Sauceda Torres',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '3°',
                'seccion'        => '1',
                'aula'           => 7,
                'jornada'        => 'Matutina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1987-00005',
                'fecha_nacimiento'=> '1987-11-25',
                'fecha_ingreso'  => '2016-01-20',
            ],
            [
                'nombre'         => 'Elia Jezabel',
                'apellido'       => 'Sosa Romero',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '3°',
                'seccion'        => '2',
                'aula'           => 6,
                'jornada'        => 'Matutina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1992-00006',
                'fecha_nacimiento'=> '1992-04-08',
                'fecha_ingreso'  => '2019-02-15',
            ],
            [
                'nombre'         => 'Mirian Fidelia',
                'apellido'       => 'Carias Cálix',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '4°',
                'seccion'        => '1',
                'aula'           => 12,
                'jornada'        => 'Matutina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1983-00007',
                'fecha_nacimiento'=> '1983-07-30',
                'fecha_ingreso'  => '2012-03-01',
            ],
            [
                'nombre'         => 'Rolan Armando',
                'apellido'       => 'Espinal Pavón',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '4°',
                'seccion'        => '2',
                'aula'           => 14,
                'jornada'        => 'Matutina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1980-00008',
                'fecha_nacimiento'=> '1980-12-05',
                'fecha_ingreso'  => '2010-01-15',
            ],
            [
                'nombre'         => 'Ángel Adolfo',
                'apellido'       => 'Sánchez Godoy',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '5°',
                'seccion'        => '1',
                'aula'           => 10,
                'jornada'        => 'Matutina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1986-00009',
                'fecha_nacimiento'=> '1986-05-18',
                'fecha_ingreso'  => '2014-02-01',
            ],
            [
                'nombre'         => 'Pedro Gustavo',
                'apellido'       => 'Nufio Zelaya',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '5°',
                'seccion'        => '2',
                'aula'           => 11,
                'jornada'        => 'Matutina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1984-00010',
                'fecha_nacimiento'=> '1984-08-22',
                'fecha_ingreso'  => '2013-03-10',
            ],
            [
                'nombre'         => 'Bivilia Jamileth',
                'apellido'       => 'Salgado Molina',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '6°',
                'seccion'        => '1',
                'aula'           => 15,
                'jornada'        => 'Matutina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1979-00011',
                'fecha_nacimiento'=> '1979-02-14',
                'fecha_ingreso'  => '2008-01-20',
            ],
            [
                'nombre'         => 'Bernarda Leticia',
                'apellido'       => 'Turcios Andino',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '6°',
                'seccion'        => '2',
                'aula'           => 13,
                'jornada'        => 'Matutina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1981-00012',
                'fecha_nacimiento'=> '1981-10-03',
                'fecha_ingreso'  => '2009-02-15',
            ],
            [
                'nombre'         => 'Nancy Margoth',
                'apellido'       => 'Ávila Ávila',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '6°',
                'seccion'        => '3',
                'aula'           => 16,
                'jornada'        => 'Matutina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1982-00013',
                'fecha_nacimiento'=> '1982-06-28',
                'fecha_ingreso'  => '2011-01-10',
            ],
            [
                'nombre'         => 'Leda Danelia',
                'apellido'       => 'Ávila Ortíz',
                'especialidad'   => 'Informática',
                'grado'          => 'Informática',
                'seccion'        => 'Matutina',
                'aula'           => null,
                'jornada'        => 'Matutina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1989-00014',
                'fecha_nacimiento'=> '1989-03-12',
                'fecha_ingreso'  => '2019-01-15',
            ],
            [
                'nombre'         => 'Francis Judith',
                'apellido'       => 'Reyes Sosa',
                'especialidad'   => 'Biblioteca',
                'grado'          => 'Biblioteca',
                'seccion'        => 'Matutina',
                'aula'           => null,
                'jornada'        => 'Matutina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1993-00015',
                'fecha_nacimiento'=> '1993-07-19',
                'fecha_ingreso'  => '2022-02-01',
            ],

            // ══════════════════════════════════════════════════════════════
            // JORNADA VESPERTINA
            // Sub Directora: Jade Manuela Lopez
            // ══════════════════════════════════════════════════════════════

            [
                'nombre'         => 'Lourdes Suyapa',
                'apellido'       => 'Maradiaga Bonilla',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '1°',
                'seccion'        => '3',
                'aula'           => 2,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1988-00016',
                'fecha_nacimiento'=> '1988-01-15',
                'fecha_ingreso'  => '2017-03-01',
            ],
            [
                'nombre'         => 'Sayda Karina',
                'apellido'       => 'García Murillo',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '2°',
                'seccion'        => '3',
                'aula'           => 1,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1990-00017',
                'fecha_nacimiento'=> '1990-05-22',
                'fecha_ingreso'  => '2019-02-10',
            ],
            [
                'nombre'         => 'Aminta Isabel',
                'apellido'       => 'Rojas Zelaya',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '3°',
                'seccion'        => '3',
                'aula'           => 7,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1985-00018',
                'fecha_nacimiento'=> '1985-09-08',
                'fecha_ingreso'  => '2015-01-20',
            ],
            [
                'nombre'         => 'Claudia Lizeth',
                'apellido'       => 'Artica Soto',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '3°',
                'seccion'        => '4',
                'aula'           => 8,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1987-00019',
                'fecha_nacimiento'=> '1987-12-03',
                'fecha_ingreso'  => '2016-03-15',
            ],
            [
                'nombre'         => 'Sofía Evelin',
                'apellido'       => 'Briseño Lemus',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '4°',
                'seccion'        => '3',
                'aula'           => 13,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1991-00020',
                'fecha_nacimiento'=> '1991-04-17',
                'fecha_ingreso'  => '2020-02-01',
            ],
            [
                'nombre'         => 'Aida Elizabeth',
                'apellido'       => 'Lewis Belez',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '4°',
                'seccion'        => '4',
                'aula'           => 10,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1986-00021',
                'fecha_nacimiento'=> '1986-07-30',
                'fecha_ingreso'  => '2016-01-15',
            ],
            [
                'nombre'         => 'Francis Rafaela',
                'apellido'       => 'Valladares C',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '5°',
                'seccion'        => '3',
                'aula'           => 11,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1983-00022',
                'fecha_nacimiento'=> '1983-02-11',
                'fecha_ingreso'  => '2013-02-01',
            ],
            [
                'nombre'         => 'Xiomara Marisol',
                'apellido'       => 'Gómez Zelaya',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '5°',
                'seccion'        => '4',
                'aula'           => 9,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1989-00023',
                'fecha_nacimiento'=> '1989-10-25',
                'fecha_ingreso'  => '2018-03-10',
            ],
            [
                'nombre'         => 'Nancy Jamileth',
                'apellido'       => 'Ramírez Miranda',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '6°',
                'seccion'        => '4',
                'aula'           => 14,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1984-00024',
                'fecha_nacimiento'=> '1984-08-14',
                'fecha_ingreso'  => '2014-01-20',
            ],
            [
                'nombre'         => 'Ruth Lizeth',
                'apellido'       => 'Salinas Mendoza',
                'especialidad'   => 'Educación Primaria',
                'grado'          => '6°',
                'seccion'        => '5',
                'aula'           => 12,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1992-00025',
                'fecha_nacimiento'=> '1992-01-06',
                'fecha_ingreso'  => '2021-03-01',
            ],
            [
                'nombre'         => 'Justina',
                'apellido'       => 'Castellanos Irías',
                'especialidad'   => 'Informática',
                'grado'          => 'Informática',
                'seccion'        => 'Vespertina',
                'aula'           => null,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1993-00026',
                'fecha_nacimiento'=> '1993-06-20',
                'fecha_ingreso'  => '2022-01-15',
            ],
            [
                'nombre'         => 'Gladys Marivel',
                'apellido'       => 'Mendoza Portillo',
                'especialidad'   => 'Biblioteca',
                'grado'          => 'Biblioteca',
                'seccion'        => 'Vespertina',
                'aula'           => null,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1980-00027',
                'fecha_nacimiento'=> '1980-11-30',
                'fecha_ingreso'  => '2010-02-01',
            ],
            [
                'nombre'         => 'Flora María',
                'apellido'       => 'González',
                'especialidad'   => 'Asistente',
                'grado'          => 'Asistente',
                'seccion'        => 'Vespertina',
                'aula'           => null,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1995-00028',
                'fecha_nacimiento'=> '1995-04-12',
                'fecha_ingreso'  => '2023-03-01',
            ],

            // ══════════════════════════════════════════════════════════════
            // III CICLO (Vespertina)
            // Docentes guía de 7°, 8°, 9°
            // ══════════════════════════════════════════════════════════════

            [
                'nombre'         => 'Carlos José',
                'apellido'       => 'Oyuela Moncada',
                'especialidad'   => 'III Ciclo',
                'grado'          => '7°',
                'seccion'        => '1',
                'aula'           => 17,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1978-00029',
                'fecha_nacimiento'=> '1978-08-05',
                'fecha_ingreso'  => '2007-02-01',
            ],
            [
                'nombre'         => 'Ángela María',
                'apellido'       => 'Salinas',
                'especialidad'   => 'III Ciclo',
                'grado'          => '8°',
                'seccion'        => '1',
                'aula'           => 16,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1982-00030',
                'fecha_nacimiento'=> '1982-03-18',
                'fecha_ingreso'  => '2011-03-01',
            ],
            [
                'nombre'         => 'Karla Vanessa',
                'apellido'       => 'Sauceda Iglesias',
                'especialidad'   => 'III Ciclo',
                'grado'          => '9°',
                'seccion'        => '1',
                'aula'           => 15,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1990-00031',
                'fecha_nacimiento'=> '1990-11-22',
                'fecha_ingreso'  => '2019-03-10',
            ],
            [
                'nombre'         => 'Blanca Azucena',
                'apellido'       => 'Salinas Chavarria',
                'especialidad'   => 'Consejería',
                'grado'          => 'Consejera',
                'seccion'        => '7°,8°,9°',
                'aula'           => null,
                'jornada'        => 'Vespertina',
                'tipo_contrato'  => 'tiempo_completo',
                'dni'            => '0101-1979-00032',
                'fecha_nacimiento'=> '1979-06-09',
                'fecha_ingreso'  => '2009-01-20',
            ],
        ];

        foreach ($profesores as $datos) {
            // Extraemos los campos extra (no están en la migración)
            // pero los dejamos aquí documentados para referencia
            $grado   = $datos['grado'];
            $seccion = $datos['seccion'];
            $aula    = $datos['aula'];
            $jornada = $datos['jornada'];

            DB::table('profesores')->insertOrIgnore([
                'nombre'          => $datos['nombre'],
                'apellido'        => $datos['apellido'],
                'email'           => null,   // Sin email en las listas — actualizar con datos reales
                'telefono'        => null,   // Sin teléfono en las listas — actualizar con datos reales
                'dni'             => $datos['dni'],
                'fecha_nacimiento'=> $datos['fecha_nacimiento'],
                'direccion'       => null,
                'especialidad'      => $datos['especialidad'],
                'genero'            => null,   // Actualizar con datos reales
                'nivel_academico'   => null,   // Actualizar con datos reales
                'salario'           => null,
                'tipo_contrato'     => $datos['tipo_contrato'],
                'fecha_contratacion'=> $datos['fecha_ingreso'],
                'observaciones'   => "Jornada: {$jornada} | Grado: {$grado} | Sección: {$seccion}" . ($aula ? " | Aula: {$aula}" : ''),
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ]);
        }

        $this->command->info('✅ ' . count($profesores) . ' profesores insertados correctamente.');
        $this->command->warn('⚠️  Recuerda actualizar los DNI, fechas de nacimiento y salarios con los datos reales.');
    }
}
