<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class ProfesorSeeder extends Seeder
{
    public function run(): void
    {
        // Obtener el ID del rol Maestro (si ya fue creado por RolesPermisosSeeder)
        $maestroRolId = DB::table('roles')->where('nombre', 'Maestro')->value('id');

        $profesores = [

            // ══════════════════════════════════════════════════════════════
            // JORNADA MATUTINA
            // Director: Edwin Orlando Amador Mejia
            // ══════════════════════════════════════════════════════════════

            [
                'nombre'           => 'Jennifer Jeanneth',
                'apellido'         => 'Mascareño Mairena',
                'email'            => 'jennifer.mascareno@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '1°',
                'seccion'          => '1',
                'aula'             => 9,
                'jornada'          => 'Matutina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101199000001',
                'fecha_nacimiento' => '1990-01-01',
                'fecha_ingreso'    => '2020-01-15',
            ],
            [
                // Nota: en la imagen aparece tachada "Ana Melissa Valladares Castillo"
                // y sustituida por "Concepción Jamileth Sierra"
                'nombre'           => 'Concepción Jamileth',
                'apellido'         => 'Sierra',
                'email'            => 'concepcion.sierra@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '1°',
                'seccion'          => '2',
                'aula'             => 2,
                'jornada'          => 'Matutina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101199100002',
                'fecha_nacimiento' => '1991-03-15',
                'fecha_ingreso'    => '2023-01-10',
            ],
            [
                'nombre'           => 'Juana Magdalena',
                'apellido'         => 'León Centeno',
                'email'            => 'juana.leon@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '2°',
                'seccion'          => '1',
                'aula'             => 1,
                'jornada'          => 'Matutina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198500003',
                'fecha_nacimiento' => '1985-06-20',
                'fecha_ingreso'    => '2015-02-01',
            ],
            [
                'nombre'           => 'Liz Dionelsy',
                'apellido'         => 'Veliz Escoto',
                'email'            => 'liz.veliz@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '2°',
                'seccion'          => '2',
                'aula'             => 4,
                'jornada'          => 'Matutina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198800004',
                'fecha_nacimiento' => '1988-09-10',
                'fecha_ingreso'    => '2018-03-01',
            ],
            [
                'nombre'           => 'Paula Melissa',
                'apellido'         => 'Sauceda Torres',
                'email'            => 'paula.sauceda@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '3°',
                'seccion'          => '1',
                'aula'             => 7,
                'jornada'          => 'Matutina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198700005',
                'fecha_nacimiento' => '1987-11-25',
                'fecha_ingreso'    => '2016-01-20',
            ],
            [
                'nombre'           => 'Elia Jezabel',
                'apellido'         => 'Sosa Romero',
                'email'            => 'elia.sosa@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '3°',
                'seccion'          => '2',
                'aula'             => 6,
                'jornada'          => 'Matutina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101199200006',
                'fecha_nacimiento' => '1992-04-08',
                'fecha_ingreso'    => '2019-02-15',
            ],
            [
                'nombre'           => 'Mirian Fidelia',
                'apellido'         => 'Carias Cálix',
                'email'            => 'mirian.carias@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '4°',
                'seccion'          => '1',
                'aula'             => 12,
                'jornada'          => 'Matutina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198300007',
                'fecha_nacimiento' => '1983-07-30',
                'fecha_ingreso'    => '2012-03-01',
            ],
            [
                'nombre'           => 'Rolan Armando',
                'apellido'         => 'Espinal Pavón',
                'email'            => 'rolan.espinal@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '4°',
                'seccion'          => '2',
                'aula'             => 14,
                'jornada'          => 'Matutina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198000008',
                'fecha_nacimiento' => '1980-12-05',
                'fecha_ingreso'    => '2010-01-15',
            ],
            [
                'nombre'           => 'Ángel Adolfo',
                'apellido'         => 'Sánchez Godoy',
                'email'            => 'angel.sanchez@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '5°',
                'seccion'          => '1',
                'aula'             => 10,
                'jornada'          => 'Matutina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198600009',
                'fecha_nacimiento' => '1986-05-18',
                'fecha_ingreso'    => '2014-02-01',
            ],
            [
                'nombre'           => 'Pedro Gustavo',
                'apellido'         => 'Nufio Zelaya',
                'email'            => 'pedro.nufio@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '5°',
                'seccion'          => '2',
                'aula'             => 11,
                'jornada'          => 'Matutina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198400010',
                'fecha_nacimiento' => '1984-08-22',
                'fecha_ingreso'    => '2013-03-10',
            ],
            [
                'nombre'           => 'Bivilia Jamileth',
                'apellido'         => 'Salgado Molina',
                'email'            => 'bivilia.salgado@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '6°',
                'seccion'          => '1',
                'aula'             => 15,
                'jornada'          => 'Matutina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101197900011',
                'fecha_nacimiento' => '1979-02-14',
                'fecha_ingreso'    => '2008-01-20',
            ],
            [
                'nombre'           => 'Bernarda Leticia',
                'apellido'         => 'Turcios Andino',
                'email'            => 'bernarda.turcios@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '6°',
                'seccion'          => '2',
                'aula'             => 13,
                'jornada'          => 'Matutina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198100012',
                'fecha_nacimiento' => '1981-10-03',
                'fecha_ingreso'    => '2009-02-15',
            ],
            [
                'nombre'           => 'Nancy Margoth',
                'apellido'         => 'Ávila Ávila',
                'email'            => 'nancy.avila@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '6°',
                'seccion'          => '3',
                'aula'             => 16,
                'jornada'          => 'Matutina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198200013',
                'fecha_nacimiento' => '1982-06-28',
                'fecha_ingreso'    => '2011-01-10',
            ],
            [
                'nombre'           => 'Leda Danelia',
                'apellido'         => 'Ávila Ortíz',
                'email'            => 'leda.avila@egm.edu.hn',
                'especialidad'     => 'Informática',
                'grado'            => 'Informática',
                'seccion'          => 'Matutina',
                'aula'             => null,
                'jornada'          => 'Matutina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198900014',
                'fecha_nacimiento' => '1989-03-12',
                'fecha_ingreso'    => '2019-01-15',
            ],
            [
                'nombre'           => 'Francis Judith',
                'apellido'         => 'Reyes Sosa',
                'email'            => 'francis.reyes@egm.edu.hn',
                'especialidad'     => 'Biblioteca',
                'grado'            => 'Biblioteca',
                'seccion'          => 'Matutina',
                'aula'             => null,
                'jornada'          => 'Matutina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101199300015',
                'fecha_nacimiento' => '1993-07-19',
                'fecha_ingreso'    => '2022-02-01',
            ],

            // ══════════════════════════════════════════════════════════════
            // JORNADA VESPERTINA
            // Sub Directora: Jade Manuela Lopez
            // ══════════════════════════════════════════════════════════════

            [
                'nombre'           => 'Lourdes Suyapa',
                'apellido'         => 'Maradiaga Bonilla',
                'email'            => 'lourdes.maradiaga@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '1°',
                'seccion'          => '3',
                'aula'             => 2,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198800016',
                'fecha_nacimiento' => '1988-01-15',
                'fecha_ingreso'    => '2017-03-01',
            ],
            [
                'nombre'           => 'Sayda Karina',
                'apellido'         => 'García Murillo',
                'email'            => 'sayda.garcia@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '2°',
                'seccion'          => '3',
                'aula'             => 1,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101199000017',
                'fecha_nacimiento' => '1990-05-22',
                'fecha_ingreso'    => '2019-02-10',
            ],
            [
                'nombre'           => 'Aminta Isabel',
                'apellido'         => 'Rojas Zelaya',
                'email'            => 'aminta.rojas@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '3°',
                'seccion'          => '3',
                'aula'             => 7,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198500018',
                'fecha_nacimiento' => '1985-09-08',
                'fecha_ingreso'    => '2015-01-20',
            ],
            [
                'nombre'           => 'Claudia Lizeth',
                'apellido'         => 'Artica Soto',
                'email'            => 'claudia.artica@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '3°',
                'seccion'          => '4',
                'aula'             => 8,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198700019',
                'fecha_nacimiento' => '1987-12-03',
                'fecha_ingreso'    => '2016-03-15',
            ],
            [
                'nombre'           => 'Sofía Evelin',
                'apellido'         => 'Briseño Lemus',
                'email'            => 'sofia.briseno@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '4°',
                'seccion'          => '3',
                'aula'             => 13,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101199100020',
                'fecha_nacimiento' => '1991-04-17',
                'fecha_ingreso'    => '2020-02-01',
            ],
            [
                'nombre'           => 'Aida Elizabeth',
                'apellido'         => 'Lewis Belez',
                'email'            => 'aida.lewis@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '4°',
                'seccion'          => '4',
                'aula'             => 10,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198600021',
                'fecha_nacimiento' => '1986-07-30',
                'fecha_ingreso'    => '2016-01-15',
            ],
            [
                'nombre'           => 'Francis Rafaela',
                'apellido'         => 'Valladares C',
                'email'            => 'francis.valladares@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '5°',
                'seccion'          => '3',
                'aula'             => 11,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198300022',
                'fecha_nacimiento' => '1983-02-11',
                'fecha_ingreso'    => '2013-02-01',
            ],
            [
                'nombre'           => 'Xiomara Marisol',
                'apellido'         => 'Gómez Zelaya',
                'email'            => 'xiomara.gomez@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '5°',
                'seccion'          => '4',
                'aula'             => 9,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198900023',
                'fecha_nacimiento' => '1989-10-25',
                'fecha_ingreso'    => '2018-03-10',
            ],
            [
                'nombre'           => 'Nancy Jamileth',
                'apellido'         => 'Ramírez Miranda',
                'email'            => 'nancy.ramirez@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '6°',
                'seccion'          => '4',
                'aula'             => 14,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198400024',
                'fecha_nacimiento' => '1984-08-14',
                'fecha_ingreso'    => '2014-01-20',
            ],
            [
                'nombre'           => 'Ruth Lizeth',
                'apellido'         => 'Salinas Mendoza',
                'email'            => 'ruth.salinas@egm.edu.hn',
                'especialidad'     => 'Educación Primaria',
                'grado'            => '6°',
                'seccion'          => '5',
                'aula'             => 12,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101199200025',
                'fecha_nacimiento' => '1992-01-06',
                'fecha_ingreso'    => '2021-03-01',
            ],
            [
                'nombre'           => 'Justina',
                'apellido'         => 'Castellanos Irías',
                'email'            => 'justina.castellanos@egm.edu.hn',
                'especialidad'     => 'Informática',
                'grado'            => 'Informática',
                'seccion'          => 'Vespertina',
                'aula'             => null,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101199300026',
                'fecha_nacimiento' => '1993-06-20',
                'fecha_ingreso'    => '2022-01-15',
            ],
            [
                'nombre'           => 'Gladys Marivel',
                'apellido'         => 'Mendoza Portillo',
                'email'            => 'gladys.mendoza@egm.edu.hn',
                'especialidad'     => 'Biblioteca',
                'grado'            => 'Biblioteca',
                'seccion'          => 'Vespertina',
                'aula'             => null,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198000027',
                'fecha_nacimiento' => '1980-11-30',
                'fecha_ingreso'    => '2010-02-01',
            ],
            [
                'nombre'           => 'Flora María',
                'apellido'         => 'González',
                'email'            => 'flora.gonzalez@egm.edu.hn',
                'especialidad'     => 'Asistente',
                'grado'            => 'Asistente',
                'seccion'          => 'Vespertina',
                'aula'             => null,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101199500028',
                'fecha_nacimiento' => '1995-04-12',
                'fecha_ingreso'    => '2023-03-01',
            ],

            // ══════════════════════════════════════════════════════════════
            // III CICLO (Vespertina)
            // Docentes guía de 7°, 8°, 9°
            // ══════════════════════════════════════════════════════════════

            [
                'nombre'           => 'Carlos José',
                'apellido'         => 'Oyuela Moncada',
                'email'            => 'carlos.oyuela@egm.edu.hn',
                'especialidad'     => 'III Ciclo',
                'grado'            => '7°',
                'seccion'          => '1',
                'aula'             => 17,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101197800029',
                'fecha_nacimiento' => '1978-08-05',
                'fecha_ingreso'    => '2007-02-01',
            ],
            [
                'nombre'           => 'Ángela María',
                'apellido'         => 'Salinas',
                'email'            => 'angela.salinas@egm.edu.hn',
                'especialidad'     => 'III Ciclo',
                'grado'            => '8°',
                'seccion'          => '1',
                'aula'             => 16,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101198200030',
                'fecha_nacimiento' => '1982-03-18',
                'fecha_ingreso'    => '2011-03-01',
            ],
            [
                'nombre'           => 'Karla Vanessa',
                'apellido'         => 'Sauceda Iglesias',
                'email'            => 'karla.sauceda@egm.edu.hn',
                'especialidad'     => 'III Ciclo',
                'grado'            => '9°',
                'seccion'          => '1',
                'aula'             => 15,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101199000031',
                'fecha_nacimiento' => '1990-11-22',
                'fecha_ingreso'    => '2019-03-10',
            ],
            [
                'nombre'           => 'Blanca Azucena',
                'apellido'         => 'Salinas Chavarria',
                'email'            => 'blanca.salinas@egm.edu.hn',
                'especialidad'     => 'Consejería',
                'grado'            => 'Consejera',
                'seccion'          => '7°,8°,9°',
                'aula'             => null,
                'jornada'          => 'Vespertina',
                'tipo_contrato'    => 'tiempo_completo',
                'dni'              => '0101197900032',
                'fecha_nacimiento' => '1979-06-09',
                'fecha_ingreso'    => '2009-01-20',
            ],
        ];

        $contadorProfesores = 0;
        $contadorUsuarios   = 0;

        foreach ($profesores as $datos) {
            $grado   = $datos['grado'];
            $seccion = $datos['seccion'];
            $aula    = $datos['aula'];
            $jornada = $datos['jornada'];
            $email   = $datos['email'];

            // 1) Insertar (o ignorar si ya existe) el registro en profesores
            $inserted = DB::table('profesores')->insertOrIgnore([
                'nombre'             => $datos['nombre'],
                'apellido'           => $datos['apellido'],
                'email'              => $email,
                'telefono'           => null,
                'dni'                => $datos['dni'],
                'fecha_nacimiento'   => $datos['fecha_nacimiento'],
                'direccion'          => null,
                'especialidad'       => $datos['especialidad'],
                'genero'             => null,
                'nivel_academico'    => null,
                'salario'            => null,
                'tipo_contrato'      => $datos['tipo_contrato'],
                'fecha_contratacion' => $datos['fecha_ingreso'],
                'observaciones'      => "Jornada: {$jornada} | Grado: {$grado} | Sección: {$seccion}" . ($aula ? " | Aula: {$aula}" : ''),
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ]);

            if ($inserted) {
                $contadorProfesores++;
            }

            // 2) Crear el usuario si no existe (se vincula al profesor por email)
            $existeUsuario = DB::table('users')->where('email', $email)->exists();

            if (! $existeUsuario) {
                DB::table('users')->insert([
                    'name'              => $datos['nombre'] . ' ' . $datos['apellido'],
                    'email'             => $email,
                    'password'          => Hash::make('Docente2025!'),
                    'user_type'         => 'profesor',
                    'id_rol'            => $maestroRolId,
                    'activo'            => true,
                    'is_super_admin'    => false,
                    'is_protected'      => false,
                    'email_verified_at' => Carbon::now(),
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ]);
                $contadorUsuarios++;
            }
        }

        $this->command->info("✅ {$contadorProfesores} profesores insertados en tabla profesores.");
        $this->command->info("✅ {$contadorUsuarios} usuarios creados para los docentes.");
        $this->command->line('');
        $this->command->line('  Contraseña por defecto : Docente2025!');
        $this->command->line('  Formato de correos     : nombre.apellido@egm.edu.hn');
        $this->command->line('');
        $this->command->warn('⚠️  Recuerda actualizar los DNI, fechas de nacimiento y salarios con los datos reales.');
        $this->command->warn('⚠️  Cada docente debe cambiar su contraseña al primer inicio de sesión.');
    }
}
